name: github-quiz-multiOS

on: 
  push: 
    branches:
    - main
    - staging
  pull_request:

jobs:
  quiz-multiOS:
    runs-on: ubuntu-22.04 
    strategy: 
      matrix: # matrix is must. os/py-vers(python version) is a independent variable
        # os:  [ubuntu-latest, ubuntu-22.04]
        py-vers: ['Python 3.11', 'Python 3.12', 'Python 3.14']
    
    steps:
    - name: check codes 
      uses: actions/checkout@v4
    - name: configure multiple python versions 
      uses: actions/setup-python@v5 
      with:
        python-version: ${{ matrix.py-vers }}

    - name: install dependencies
      run: pip install -r requirements.txt
    - name: test 
      run: pytest

# To use multiple python version 
# have to assign it under a variable 
# strategy: 
#   matrix: # matrix is must. os/py-vers(python version) is a independent variable
#     os: [ os1, os2 ]
#     python-version: ['py.v1', 'py.v2']
# runs-on: $${{ matrix.os }}
# steps: 
# - name: 
#   uses: action/setup-python@v5
#   with: 
#     python-version: ${{ matrix.python-version }}
# 
# 
# 
